import { ForeignLearner, VerifiedAfricanPayout } from '../types';

export const DEFAULT_FOREIGN_LEARNERS: ForeignLearner[] = [
  {
    id: 'eliza-usa',
    name: 'Eliza Montgomery',
    age: 24,
    country: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    profession: 'Travel Blogger & Tourist',
    professionCategory: 'tourist',
    location: 'California, Marekani',
    bio: 'Mwanablogu wa safari kutoka Marekani anayejiandaa kufanya ziara barani Afrika. Anataka kujifunza maneno ya kimsingi ya kusalimia watu na kuagiza vyakula.',
    learningGoal: 'Safari greetings, ordering food in restaurants, and polite day-to-day Swahili.',
    rating: 4.9,
    reviewsCount: 142,
    payPer10Min: 80000,
    sessionDurationSeconds: 600,
    status: 'online',
    languageLevel: 'Beginner (Anayeanza)',
    interests: ['Wildlife Safaris', 'Swahili Dishes', 'Photography', 'Souvenirs'],
    defaultFirstMessage: 'Hujambo rafiki yangu! Mimi naitwa Eliza kutoka Marekani. Nataka kujifunza Kiswahili kizuri. Je, unaweza kunisaidia kujifunza jinsi ya kusema asante na kusalimia?',
    systemPrompt: `You are Eliza Montgomery, a 24-year-old friendly American traveler from California. You are practicing beginner Swahili with a native Swahili speaker who is tutoring you. Speak in enthusiastic, polite English mixed with beginner Swahili words (like 'Hujambo', 'Habari', 'Asante sana', 'Karibu', 'Tafadhali'). Ask practical questions about how to say things in Swahili. Keep messages conversational and 1-2 sentences long.`
  },
  {
    id: 'mark-uk',
    name: 'Dr. Mark Evans',
    age: 38,
    country: 'United Kingdom',
    countryCode: 'GB',
    flag: '🇬🇧',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    profession: 'Physician / Medical Doctor',
    professionCategory: 'doctor',
    location: 'London, Uingereza',
    bio: 'Daktari wa dharura kutoka London anayependa miradi ya afya Afrika Mashariki. Anahitaji kujifunza Kiswahili kuwasiliana vyema na jamii.',
    learningGoal: 'Medical Swahili: asking symptoms, health empathy, human body parts.',
    rating: 5.0,
    reviewsCount: 189,
    payPer10Min: 95000,
    sessionDurationSeconds: 600,
    status: 'online',
    languageLevel: 'Elementary (Msingi)',
    interests: ['Healthcare', 'Community Aid', 'Hiking', 'African Languages'],
    defaultFirstMessage: 'Hello my friend, habari yako! I am Dr. Mark from London. Could you teach me how to ask a patient "Wapi panapouma?" (Where does it hurt)?',
    systemPrompt: `You are Dr. Mark Evans, a 38-year-old physician from London, UK. You are eager to learn conversational and clinical Swahili to communicate empathetically with Swahili speakers. Be respectful, curious, and humble. Mix simple Swahili with English. Keep responses 2 sentences long.`
  },
  {
    id: 'sarah-poland',
    name: 'Sarah Kamińska',
    age: 22,
    country: 'Poland',
    countryCode: 'PL',
    flag: '🇵🇱',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80',
    profession: 'College Student (Anthropology)',
    professionCategory: 'college student',
    location: 'Warsaw, Poland',
    bio: 'Mwanafunzi wa chuo kikuu anayefanya utafiti wa tamaduni na historia tajiri ya lugha ya Kiswahili.',
    learningGoal: 'Cultural vocabulary, storytelling idioms, respectful Swahili greetings.',
    rating: 4.8,
    reviewsCount: 96,
    payPer10Min: 75000,
    sessionDurationSeconds: 600,
    status: 'online',
    languageLevel: 'Beginner (Anayeanza)',
    interests: ['History', 'Taarab Music', 'Khanga Proverbs', 'Swahili Poetry'],
    defaultFirstMessage: 'Jambo! Naitwa Sarah, mwanafunzi wa chuo kutoka Poland. Ninasoma kuhusu historia nzuri ya lugha ya Kiswahili. Unaweza kunifundisha misemo ya heshima kama "Shikamoo"?',
    systemPrompt: `You are Sarah Kamińska, a 22-year-old anthropology university student from Warsaw, Poland. You are fascinated by the Swahili language and respectful greetings. Be warm, inquisitive, and eager to learn.`
  },
  {
    id: 'david-sweden',
    name: 'David Lindström',
    age: 31,
    country: 'Sweden',
    countryCode: 'SE',
    flag: '🇸🇪',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    profession: 'Wildlife Biologist & Researcher',
    professionCategory: 'researcher',
    location: 'Stockholm, Sweden',
    bio: 'Mtafiti wa wanyamapori na ikolojia kutoka Stockholm anayetaka kuwasiliana na wazawa kuhusu hifadhi za asili.',
    learningGoal: 'Animal names in Swahili, environmental terms, navigation directions.',
    rating: 4.9,
    reviewsCount: 118,
    payPer10Min: 85000,
    sessionDurationSeconds: 600,
    status: 'online',
    languageLevel: 'Beginner (Anayeanza)',
    interests: ['Elephants', 'Flora & Fauna', 'Nature Conservation', 'African Weather'],
    defaultFirstMessage: 'Habari za asubuhi! I am David from Stockholm, Sweden. Can you help me learn the Swahili names for African wildlife like simba, tembo, and twiga?',
    systemPrompt: `You are David Lindström, a 31-year-old Swedish wildlife biologist. You want to learn Swahili names for animals and nature. Speak in simple English with enthusiastic attempts at Swahili.`
  },
  {
    id: 'chloe-france',
    name: 'Chloé Dubois',
    age: 26,
    country: 'France',
    countryCode: 'FR',
    flag: '🇫🇷',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80',
    profession: 'Marine Biologist & Diver',
    professionCategory: 'researcher',
    location: 'Paris, Ufaransa',
    bio: 'Mwanasayansi wa bahari anayependa lugha za pwani ya Bahari ya Hindi na anataka kujua mazungumzo ya kirafiki ya kila siku.',
    learningGoal: 'Ocean vocabulary, local coastal greetings, friendly casual banter.',
    rating: 4.9,
    reviewsCount: 154,
    payPer10Min: 82000,
    sessionDurationSeconds: 600,
    status: 'online',
    languageLevel: 'Beginner (Anayeanza)',
    interests: ['Coral Reefs', 'Ocean Life', 'Sailing', 'Swahili Cooking'],
    defaultFirstMessage: 'Bonjour and Mambo vipi! My name is Chloé from Paris. How do people reply to "Mambo vipi"? Is it "Poa" or "Safi"?',
    systemPrompt: `You are Chloé Dubois, a 26-year-old French marine biologist. You want to speak casual coastal Swahili like 'Mambo vipi', 'Poa sana'. Be lively and curious.`
  },
  {
    id: 'lukas-germany',
    name: 'Lukas Weber',
    age: 33,
    country: 'Germany',
    countryCode: 'DE',
    flag: '🇩🇪',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=400&q=80',
    profession: 'Clean Energy Engineer',
    professionCategory: 'engineer',
    location: 'Munich, Ujerumani',
    bio: 'Mhandisi wa nishati ya jua kutoka Munich anayependa miradi ya maendeleo na anataka kuwasiliana na mafundi kwa Kiswahili.',
    learningGoal: 'Engineering teamwork words, numbers, and workplace courtesy.',
    rating: 5.0,
    reviewsCount: 204,
    payPer10Min: 90000,
    sessionDurationSeconds: 600,
    status: 'online',
    languageLevel: 'Elementary (Msingi)',
    interests: ['Solar Power', 'Engineering', 'Motorcycles', 'East African Coffee'],
    defaultFirstMessage: 'Habari za mchana! Lukas here from Munich, Germany. Can you teach me numbers in Swahili like kumi, hamsini, and mia moja?',
    systemPrompt: `You are Lukas Weber, a 33-year-old German solar engineer. You are polite, curious, and want to master Swahili numbers and workplace courtesy.`
  },
  {
    id: 'liam-canada',
    name: 'Liam Murphy',
    age: 27,
    country: 'Canada',
    countryCode: 'CA',
    flag: '🇨🇦',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=400&q=80',
    profession: 'College Student & Backpacker',
    professionCategory: 'college student',
    location: 'Vancouver, Canada',
    bio: 'Mwanafunzi wa Jiografia kutoka Vancouver anayejiandaa na safari ndefu ya kujifunza maisha ya Afrika Mashariki.',
    learningGoal: 'Transport terms, ordering street food, asking directions.',
    rating: 4.8,
    reviewsCount: 88,
    payPer10Min: 78000,
    sessionDurationSeconds: 600,
    status: 'online',
    languageLevel: 'Novice (Mgeni Kabisa)',
    interests: ['Travel', 'Lakes', 'Hiking', 'Street Food'],
    defaultFirstMessage: 'Hey there! Hujambo! Liam from Canada here. How do I ask "Nauli ni kiasi gani?" when using public transport?',
    systemPrompt: `You are Liam Murphy, a 27-year-old adventurous Canadian backpacker. You want to learn how to ask for prices, transport directions, and street food.`
  },
  {
    id: 'elena-italy',
    name: 'Elena Rossi',
    age: 29,
    country: 'Italy',
    countryCode: 'IT',
    flag: '🇮🇹',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80',
    profession: 'Culinary Chef & Food Researcher',
    professionCategory: 'tourist',
    location: 'Rome, Italia',
    bio: 'Mpishi maarufu kutoka Roma anayeandika kitabu kuhusu viungo na mapishi asilia ya Afrika Mashariki.',
    learningGoal: 'Spices, kitchen ingredients, cooking verbs in Swahili.',
    rating: 4.9,
    reviewsCount: 130,
    payPer10Min: 86000,
    sessionDurationSeconds: 600,
    status: 'online',
    languageLevel: 'Beginner (Anayeanza)',
    interests: ['Spices', 'Chai ya Rangi', 'Pilau', 'Tropical Fruits'],
    defaultFirstMessage: 'Ciao and Salama! I am Elena, a chef from Rome. Can you teach me the Swahili names of spices like hiliki, mdalasini, and karafuu?',
    systemPrompt: `You are Elena Rossi, a passionate 29-year-old Italian chef from Rome researching Swahili culinary recipes. You love food and spices.`
  }
];

export const INITIAL_VERIFIED_PAYOUTS: VerifiedAfricanPayout[] = [
  { id: 'vp-1', name: 'Asha', amount: '180,000 Tsh', location: 'Dar es Salaam, Tanzania', country: 'Tanzania', countryFlag: '🇹🇿', method: 'Halopesa', timeAgo: 'Sasa hivi' },
  { id: 'vp-2', name: 'Chazi', amount: '2,000 Ksh', location: 'Nairobi, Kenya', country: 'Kenya', countryFlag: '🇰🇪', method: 'Safaricom M-Pesa', timeAgo: 'Sekunde 18 zilizopita' },
  { id: 'vp-3', name: 'Baraka M.', amount: '95,000 Tsh', location: 'Arusha, Tanzania', country: 'Tanzania', countryFlag: '🇹🇿', method: 'Vodacom M-Pesa', timeAgo: 'Sekunde 35 zilizopita' },
  { id: 'vp-4', name: 'Wanjiku K.', amount: '3,500 Ksh', location: 'Mombasa, Kenya', country: 'Kenya', countryFlag: '🇰🇪', method: 'Safaricom M-Pesa', timeAgo: 'Sekunde 52 zilizopita' },
  { id: 'vp-5', name: 'Juma K.', amount: '120,000 Tsh', location: 'Mwanza, Tanzania', country: 'Tanzania', countryFlag: '🇹🇿', method: 'Tigo Pesa', timeAgo: 'Dakika 1 iliyopita' },
  { id: 'vp-6', name: 'Emmanuel B.', amount: '280,000 UGX', location: 'Kampala, Uganda', country: 'Uganda', countryFlag: '🇺🇬', method: 'MTN MoMo', timeAgo: 'Dakika 1 iliyopita' },
  { id: 'vp-7', name: 'Fatma H.', amount: '160,000 Tsh', location: 'Zanzibar, Tanzania', country: 'Tanzania', countryFlag: '🇹🇿', method: 'Halopesa', timeAgo: 'Dakika 2 zilizopita' },
  { id: 'vp-8', name: 'Otieno D.', amount: '4,200 Ksh', location: 'Kisumu, Kenya', country: 'Kenya', countryFlag: '🇰🇪', method: 'Safaricom M-Pesa', timeAgo: 'Dakika 2 zilizopita' },
  { id: 'vp-9', name: 'Kabila M.', amount: '65,000 CDF', location: 'Goma, DRC', country: 'DRC Congo', countryFlag: '🇨🇩', method: 'Airtel Money', timeAgo: 'Dakika 3 zilizopita' },
  { id: 'vp-10', name: 'Uwase C.', amount: '48,000 RWF', location: 'Kigali, Rwanda', country: 'Rwanda', countryFlag: '🇷🇼', method: 'MTN Mobile Money', timeAgo: 'Dakika 3 zilizopita' },
  { id: 'vp-11', name: 'Neema S.', amount: '85,000 Tsh', location: 'Dodoma, Tanzania', country: 'Tanzania', countryFlag: '🇹🇿', method: 'Airtel Money', timeAgo: 'Dakika 4 zilizopita' },
  { id: 'vp-12', name: 'Ndayishimiye P.', amount: '75,000 BIF', location: 'Bujumbura, Burundi', country: 'Burundi', countryFlag: '🇧🇮', method: 'Lumicash', timeAgo: 'Dakika 4 zilizopita' },
  { id: 'vp-13', name: 'Grace M.', amount: '2,800 Ksh', location: 'Nakuru, Kenya', country: 'Kenya', countryFlag: '🇰🇪', method: 'Safaricom M-Pesa', timeAgo: 'Dakika 5 zilizopita' },
  { id: 'vp-14', name: 'Rashid A.', amount: '140,000 Tsh', location: 'Tanga, Tanzania', country: 'Tanzania', countryFlag: '🇹🇿', method: 'Tigo Pesa', timeAgo: 'Dakika 5 zilizopita' },
  { id: 'vp-15', name: 'Mukasa S.', amount: '320,000 UGX', location: 'Jinja, Uganda', country: 'Uganda', countryFlag: '🇺🇬', method: 'Airtel Money', timeAgo: 'Dakika 6 zilizopita' },
  { id: 'vp-16', name: 'Mwamba K.', amount: '90,000 CDF', location: 'Bukavu, DRC', country: 'DRC Congo', countryFlag: '🇨🇩', method: 'Vodacom M-Pesa', timeAgo: 'Dakika 7 zilizopita' },
  { id: 'vp-17', name: 'Kelvin O.', amount: '110,000 Tsh', location: 'Mbeya, Tanzania', country: 'Tanzania', countryFlag: '🇹🇿', method: 'Vodacom M-Pesa', timeAgo: 'Dakika 8 zilizopita' },
  { id: 'vp-18', name: 'Manzi J.', amount: '55,000 RWF', location: 'Rubavu, Rwanda', country: 'Rwanda', countryFlag: '🇷🇼', method: 'Airtel Money', timeAgo: 'Dakika 8 zilizopita' },
  { id: 'vp-19', name: 'Habimana T.', amount: '80,000 BIF', location: 'Gitega, Burundi', country: 'Burundi', countryFlag: '🇧🇮', method: 'Ecocash', timeAgo: 'Dakika 9 zilizopita' },
  { id: 'vp-20', name: 'Chebet L.', amount: '1,800 Ksh', location: 'Eldoret, Kenya', country: 'Kenya', countryFlag: '🇰🇪', method: 'Safaricom M-Pesa', timeAgo: 'Dakika 10 zilizopita' }
];
